"""GCAE adapter — bridges NOMOS typed models to the SPL Cognitive Audit Engine.

The vendored GCAE engine (:mod:`second_perspective.audit.cognitive.engine`)
expects a plain ``dict`` decision context with keys like ``decision``,
``assumptions`` (list of str), ``outcome``, ``branches``, ``text``.  This
adapter:

1. Translates a NOMOS :class:`DecisionRequest` / :class:`DecisionResult`
   into the GCAE dict context.
2. Runs the five-operator deterministic audit pipeline (NS / IAP / LCH /
   CCS / STATE).
3. Translates the GCAE output dict back into NOMOS
   :class:`CognitiveAuditReport` / :class:`CognitiveRiskFinding` models.
"""

from __future__ import annotations

from typing import Any

from ...models.enums import IssueSeverity
from ...models.schemas import (
    Assumption,
    CognitiveAuditReport,
    CognitiveRiskFinding,
    DecisionRequest,
    DecisionResult,
    ResponsibilityRef,
)
from ..cognitive import (
    CORE_PLUGINS,
    CognitiveAuditEngine,
    ResponsibilityAccount,
)


_GCAE_SEVERITY_TO_NOMOS = {
    "HALT": IssueSeverity.ERROR,
    "WARN": IssueSeverity.WARNING,
    "PASS": IssueSeverity.INFO,
    "INFO": IssueSeverity.INFO,
}


def build_gcae_context(
    request: DecisionRequest,
    result: DecisionResult,
) -> dict[str, Any]:
    """Translate NOMOS typed models into a GCAE decision-context dict.

    The GCAE engine expects::

        {
          "decision":  str,             # the decision being made (P)
          "assumptions": list[str],     # declared premises (A1..An)
          "outcome":   str,             # expected outcome (Q), if known
          "branches":  list[dict],      # per-assumption failure responses
          "text":      str,             # narrative text for NS
        }
    """
    assumptions_list = [a.statement for a in request.assumptions]

    # Build branches (failure responses) from assumption falsification_conditions
    branches: list[dict[str, str]] = []
    for a in request.assumptions:
        if a.falsification_condition:
            branches.append({
                "assumption": a.statement,
                "delta_d": a.falsification_condition,
                "assumption_id": a.id,
            })

    # Narrative text: objective + alternative names/descriptions give GCAE
    # enough material for NS (narrative strip) to scan.
    narrative_parts: list[str] = [request.objective]
    if request.time_horizon:
        narrative_parts.append(f"Time horizon: {request.time_horizon}")
    for alt in request.alternatives:
        desc = f"{alt.id}: {alt.name}"
        if alt.description:
            desc += f" — {alt.description}"
        narrative_parts.append(desc)
    text = "\n".join(narrative_parts)

    # Outcome: leading candidate(s) plus status
    if result.leading_candidate_ids:
        outcome = (
            f"Selected leading candidates: {', '.join(result.leading_candidate_ids)} "
            f"(status: {result.status.value})"
        )
    else:
        outcome = f"Decision status: {result.status.value}"

    return {
        "decision": request.objective,
        "assumptions": assumptions_list,
        "outcome": outcome,
        "branches": branches,
        "text": text,
        "_nomos_request": request,
        "_nomos_result": result,
    }


def run_gcae_audit(
    request: DecisionRequest,
    result: DecisionResult,
    policy: object | None = None,
) -> tuple[CognitiveAuditReport, dict[str, Any]]:
    """Run the five-operator GCAE audit and return (NOMOS report, raw report).

    Returns:
        (CognitiveAuditReport, raw_gcae_report_dict)
    """
    # Responsibility anchor: use the declared decision owner if available
    owner: ResponsibilityRef = request.decision_owner
    account = ResponsibilityAccount(
        organization=owner.owner if owner else "UNKNOWN",
        role=owner.role if owner.role else "decision_owner",
        stage="post_decision",
    )

    config = {
        "allowed_stages": ["pre_decision", "in_decision", "post_decision", "review"],
        "disclaimer": (
            "This cognitive audit report is generated by the SPL Cognitive Audit Engine "
            "(NS/IAP/LCH/CCS/STATE). It is a structural diagnostic only and does not "
            "substitute for human judgment."
        ),
        "custom_fields": {
            "scanner": "GCAE-vendored",
            "decision_id": request.decision_id or "PENDING",
        },
    }

    engine = CognitiveAuditEngine(account=account, config=config)
    for plugin_cls in CORE_PLUGINS:
        engine.register_plugin(plugin_cls())

    ctx = build_gcae_context(request, result)
    raw_report = engine.audit(ctx, save_log=False)

    findings = _translate_findings(raw_report)
    report = CognitiveAuditReport(
        findings=findings,
        total_findings=len(findings),
        scanner_version="GCAE-1.0.0",
    )
    return report, raw_report


def _translate_findings(raw_report: dict[str, Any]) -> list[CognitiveRiskFinding]:
    """Translate GCAE plugin outputs into NOMOS CognitiveRiskFinding list."""
    findings: list[CognitiveRiskFinding] = []
    analysis = raw_report.get("analysis", {})
    if not isinstance(analysis, dict):
        return findings

    # ── NS: narrative violations ──
    ns = analysis.get("NS", {})
    if isinstance(ns, dict):
        for v in ns.get("violations", []):
            findings.append(
                CognitiveRiskFinding(
                    code=f"NS_{v.get('rule_id', 'rhetoric')}",
                    severity=_GCAE_SEVERITY_TO_NOMOS.get(v.get("severity", "WARN"), IssueSeverity.WARNING),
                    description=v.get("description", "Narrative rhetoric detected"),
                    affected_elements=["objective"],
                    recommendation="Strip rhetorical/emotional language; state only verifiable premises.",
                )
            )

    # ── IAP: implicit assumption flags ──
    iap = analysis.get("IAP", {})
    if isinstance(iap, dict):
        for flag in iap.get("flags", []):
            findings.append(
                CognitiveRiskFinding(
                    code=f"IAP_{flag.get('flag_type', flag.get('flag_id', 'implicit'))}",
                    severity=_GCAE_SEVERITY_TO_NOMOS.get(flag.get("severity", "WARN"), IssueSeverity.WARNING),
                    description=flag.get("description", "Implicit assumption detected"),
                    affected_elements=_iap_affected_elements(flag),
                    recommendation="Declare the premise explicitly with a falsification condition and owner.",
                )
            )

    # ── LCH: fragility findings ──
    lch = analysis.get("LCH", {})
    if isinstance(lch, dict):
        weakest = lch.get("weakest_variable")
        if isinstance(weakest, dict):
            dd = weakest.get("delta_d", 0)
            if dd >= 0.7:
                sev = IssueSeverity.ERROR
            elif dd >= 0.4:
                sev = IssueSeverity.WARNING
            else:
                sev = IssueSeverity.INFO
            findings.append(
                CognitiveRiskFinding(
                    code="LCH_WEAKEST_VARIABLE",
                    severity=sev,
                    description=(
                        f"Weakest assumption: '{weakest.get('assumption','?')[:80]}' "
                        f"(Delta D = {dd}). {weakest.get('failure_scenario','')}"
                    ),
                    affected_elements=[f"assumptions.{weakest.get('index',0)}"],
                    recommendation="Add branch response / falsification path; confirm evidence quality for this assumption.",
                )
            )
        if not lch.get("has_branch_coverage", True):
            findings.append(
                CognitiveRiskFinding(
                    code="LCH_INCOMPLETE_BRANCHES",
                    severity=IssueSeverity.ERROR,
                    description="Not all assumptions have failure-branch responses; system lacks recovery paths.",
                    affected_elements=["assumptions"],
                    recommendation="Define an explicit failure-response (ΔD) for every critical assumption.",
                )
            )

    # ── CCS: causal chain checks ──
    ccs = analysis.get("CCS", {})
    if isinstance(ccs, dict):
        for check in ccs.get("checks", []):
            findings.append(
                CognitiveRiskFinding(
                    code=f"CCS_{check.get('check','chain')}",
                    severity=_GCAE_SEVERITY_TO_NOMOS.get(check.get("severity", "WARN"), IssueSeverity.WARNING),
                    description=check.get("description", "Causal chain issue detected"),
                    affected_elements=_ccs_affected_elements(check),
                    recommendation=_ccs_recommendation(check),
                )
            )

    # ── STATE: anchor status ──
    state = analysis.get("STATE", {})
    if isinstance(state, dict):
        resp = state.get("responsibility", {})
        if isinstance(resp, dict) and resp.get("is_vague"):
            findings.append(
                CognitiveRiskFinding(
                    code="STATE_VAGUE_ANCHOR",
                    severity=IssueSeverity.ERROR,
                    description=resp.get("warning", "Responsibility anchor is vague"),
                    affected_elements=["decision_owner"],
                    recommendation="Anchor responsibility to a specific, identifiable decision-maker, not a collective.",
                )
            )
        verdict = state.get("verdict", {})
        if isinstance(verdict, dict) and verdict.get("level") == "AUDIT_HALT":
            # STATE already aggregates all HALT items; do not duplicate as a new finding
            # but ensure at least one ERROR-severity finding exists (it will via the
            # plugin-level findings above).
            pass

    return findings


def _iap_affected_elements(flag: dict[str, Any]) -> list[str]:
    flag_type = flag.get("flag_type", "")
    if flag_type == "self_referential":
        return ["objective", "decision_owner"]
    if flag_type == "privilege_bypass":
        return ["constraints", "decision_owner"]
    if flag_type == "missing_assumptions":
        return ["assumptions"]
    if flag_type == "circular_justification":
        return ["objective"]
    return ["assumptions"]


def _ccs_affected_elements(check: dict[str, Any]) -> list[str]:
    check_name = check.get("check", "")
    result = check.get("result", "")
    if result == "BLACKHOLE":
        return ["assumptions", "alternatives"]
    if result == "SYSTEM_COLLAPSE":
        return ["assumptions"]
    if result in ("BROKEN", "BROKEN_AT_ROOT"):
        return ["objective"]
    if result == "MISSING_A":
        return ["assumptions"]
    if result == "MISSING_Q":
        return ["alternatives"]
    if result == "UNCOVERED":
        return ["assumptions"]
    if check_name == "inverse":
        return ["assumptions"]
    return []


def _ccs_recommendation(check: dict[str, Any]) -> str:
    result = check.get("result", "")
    if result == "BLACKHOLE":
        return "Declare the missing P/A/Q variables explicitly before re-evaluating."
    if result == "SYSTEM_COLLAPSE":
        return "Add explicit failure-branch responses (ΔD) for every critical assumption."
    if result == "COLLAPSE_RISK":
        return "Insufficient branch coverage; add more recovery paths."
    if result == "BROKEN":
        return "Causal chain P→A→Q is incomplete; declare the missing link."
    if result == "MISSING_A":
        return "Add explicit assumptions between decision and outcome."
    if result == "MISSING_Q":
        return "Declare the expected outcome/result of the decision."
    if result == "UNCOVERED":
        return "Describe a counterfactual scenario (¬P) explicitly."
    return "Review the causal chain structure."